### ISSUE TITLE
missing %item-has-title%

### ISSUE THREAD

**Issue by PhanaticD** [virustotalop/ObsidianAuctions#10]
As far as I can see there is no check for titles, only lore and enchants, this is a problem because I want to display an items title even if it does not have enchants on it. Right now in the default language.yml it looks like this

%conditional-true%%has-enchantment%
  named &f"%item-display-name%"&9%conditional-true%%has-enchantment%

so basically it wont show a item with a custom title unless it has enchants

**Comment by virustotalop** [comment]
Should be fixed as of that last commit.

**Comment by virustotalop** [comment]
Seems something is still stopping it, looking into it.

**Comment by virustotalop** [comment]
Looks like this is going to be a bit more than I first thought. The message parser needs to be partially re-written. Since its not properly adding the text after the conditional to the message. https://github.com/virustotalop/ObsidianAuctions/blob/master/src/com/flobi/floAuction/AuctionMessageManager.java#L744-L764

**Comment by virustotalop** [comment]
I'm currently busy with some of my own server stuff, plus adding other features to ObsidianAuctions. @inksquid should be working on this soon.

**Comment by virustotalop** [comment]
Well inksquid changed their github username and has not contacted me on skype. I will be looking into this issue, if anyone wants to help with it they can.

**Comment by PhanaticD** [comment]
https://github.com/virustotalop/ObsidianAuctions/blob/master/src/com/flobi/floAuction/floAuction.java#L103

This is not actually set anywhere, making the recently added %has-display-name% always be false

**Comment by virustotalop** [comment]
@PhanaticD If that is the case it should be fixed as the latest commit. I will test within the next day or so.
