### ISSUE TITLE
Auction is frozen?

### ISSUE THREAD

**Issue by Elgorond** [virustotalop/ObsidianAuctions#11]
An auction is frozen at 18 seconds left for the bidding, and people can continue to /bid.

Haven't tried reloading the plugin or restarting.

**Comment by Elgorond** [comment]
used /auc suspend and resume, and it fixed. Still not sure what caused this bug though.

**Comment by virustotalop** [comment]
Did any errors appear in the console? Can you post your log on www.pastebin.com?

**Comment by Elgorond** [comment]
No errors in console afaik. I'll post log if it happens again :/

**Comment by virustotalop** [comment]
If it happens again go ahead and open another issue. Going to be closing this.
