### ISSUE TITLE
MiniMessage exception when auctioning items with legacy formatting codes

### ISSUE THREAD

**Issue by galacticwarrior9** [virustotalop/ObsidianAuctions#124]
### Current Behavior

When you auction an item whose name is coloured using legacy section characters (`§`), the auction will not begin and the following error will be thrown in chat:

```
[12:53:12 ERROR]: [ObsidianAuctions] Exception executing command handler
com.gmail.virustotalop.obsidianauctions.shaded.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.
        <white>[<gray>Obsidian<blue>Auctions<white>] <blue><aqua>galacticwarrior9<blue> is auctioning <white>1 <green>Enchanted Book<blue> named <white>"§9Slimefun Guide"<blue> for <red>30 sec<blue>. Starting bid: <gold>$100<blue>. Bid increment: <gold>$30<blue>. Buy now: <gold>$100<blue>. Type <click:run_command:/auction info><green><hover:show_text:"<red>Click to run command!</red>"><underlined>/auction info</underlined></click><blue> for full details.
```

Here's a screenshot in case the above is too difficult to read:

![Screenshot of error message](https://i.gyazo.com/49a1e77220aa6f6e45e7ce023b8141e0.png)

### Expected Behavior

The auction should begin. 

### Steps to reproduce to the bug

1. Obtain an item whose name has been coloured using legacy section characters. In my case, I tried to auction a Slimefun Guide from a plugin called Slimefun. When the section colour code is included, the full item name is "`§9Slimefun Guide`".
2. Auction the item using `/auc start`.
3. The auction will not begin and the error described above will be thrown in console. 

This was encountered on a Paper 1.18.2 server. 

### Agreements

- [X] I have tried the latest stable build and the latest dev build
- [X] I am running a supported Minecraft version 1.12.x - 1.17.x

**Comment by virustotalop** [comment]
Nice catch, I should have a fix for this in just a bit.
