### ISSUE TITLE
Item shows different

### ISSUE THREAD

**Issue by crimsson** [virustotalop/ObsidianAuctions#136]
### Current Behavior

Hi Virus,

is it possible to use or hide the text "FROM_EXECUTABLEITEM" in auction chat?

I asked their plugin but they wanted me to ask you about this.
![image](https://user-images.githubusercontent.com/91674702/198824151-eb86c0a1-8f11-45ae-aeac-83a1efa31bfb.png)
![image](https://user-images.githubusercontent.com/91674702/198824175-c023f601-91f1-41ec-a16e-2864c8020eeb.png)

### Expected Behavior

it should show Spider instead of FROM_EXECUTABLEITEM

### Steps to reproduce to the bug

use SILK_SPAWNER activator from Executable Items plugin and then when you got the spawner, just auction start it.

### Agreements

- [X] I have tried the latest stable build and the latest dev build
- [X] I am running a supported Minecraft version 1.12.x - 1.18.x

**Comment by virustotalop** [comment]
Hey @crimsson thanks for the bug report. I'm not if you're running paper but if you do can you run `/paper dumpitem` for me while holding the item? You should just need to add part of the nbt from the spider spawner to the `en-US.yml` config in the `item_languages` folder and I can help you with that. If you're not running paper I'll find an alternative solution for you.

**Comment by crimsson** [comment]
> Hey @crimsson thanks for the bug report. I'm not if you're running paper but if you do can you run `/paper dumpitem` for me while holding the item? You should just need to add part of the nbt from the spider spawner to the `en-US.yml` config in the `item_languages` folder and I can help you with that. If you're not running paper I'll find an alternative solution for you.

![image](https://user-images.githubusercontent.com/91674702/198987397-58f28eb7-3e9a-4b72-bc6f-b963219c195e.png)

This is what I get from /paper dumpitem.
Can you advise me of what should I type in en-US.yml?

**Comment by virustotalop** [comment]
@crimsson interesting, that should be working already. Can you give me the following information.
1. Your paper version by running /ver
2. Your en-US. yml, config.yml and language.yml configs uploaded to https://pastebin.com/

**Comment by crimsson** [comment]
Sure,
![image](https://user-images.githubusercontent.com/91674702/198992404-b4f1a77a-acc1-4086-bd98-43c049e78ca7.png)

en-US: https://pastebin.com/64vFRB1v
language.yml: https://pastebin.com/EVXeLCkW

I can't provide full config.yml because of pastebin filter: https://pastebin.com/SrJdbEWD

**Comment by virustotalop** [comment]
Ahh I think I see what the issue is, this wasn't your fault this was an oversight on my part. Try adding these values to your en-US language file and then doing a reboot.
```yml
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:bat"}}}': 'Bat Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:blaze"}}}': 'Blaze Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:cave_spider"}}}': 'Cave Spider Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:cat"}}}': 'Cat Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:chicken"}}}': 'Chicken Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:cow"}}}': 'Cow Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:creeper"}}}': 'Creeper Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:donkey"}}}': 'Donkey Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:elder_guardian"}}}': 'Elder Guardian Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:enderman"}}}': 'Enderman Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:endermite"}}}': 'Endermite Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:evocation_illager"}}}': 'Evoker Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:ghast"}}}': 'Ghast Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:guardian"}}}': 'Guardian Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:horse"}}}': 'Horse Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:husk"}}}': 'Husk Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:llama"}}}': 'Llama Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:magma_cube"}}}': 'Magma Cube Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:mooshroom"}}}': 'Mooshroom Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:mule"}}}': 'Mule Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:ocelon"}}}': 'Ocelot Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:parrot"}}}': 'Parrot Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:pig"}}}': 'Pig Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:polar_bear"}}}': 'Polar Bear Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:pufferfish"}}}': 'Pufferfish Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:rabbit"}}}': 'Rabbit Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:sheep"}}}': 'Sheep Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{Color:10b,id:"minecraft:shulker"}}}': 'Shulker Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:silverfish"}}}': 'Silverfish Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:skeleton"}}}': 'Skeleton Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:skeleton_horse"}}}': 'Skeleton Horse Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:slime"}}}': 'Slime Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:spider"}}}': 'Spider Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:squid"}}}': 'Squid Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:stray"}}}': 'Stray Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:vex"}}}': 'Vex Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:villager"}}}': 'Villager Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:vindication_illager"}}}': 'Vindicator Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:witch"}}}': 'Witch Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:wither_skeleton"}}}': 'Wither Skeleton Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:wolf"}}}': 'Wolf Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:zombie"}}}': 'Zombie Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:zombie_horse"}}}': 'Zombie Horse Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:zombie_villager"}}}': 'Zombie Villager Mob Spawner'
'SPAWNER<sep>{BlockEntityTag:{SpawnData:{id:"minecraft:zombie_pigman"}}}': 'Zombie Pigman Mob Spawner'
```

**Comment by crimsson** [comment]
![image](https://user-images.githubusercontent.com/91674702/199099401-45e043b4-347f-4f09-b59f-ec6e07f68cca.png)

Thanks man, it works !


Another question, would the en_US you gave me work on 1.19.2? 'cause im planning to up my server version in the future.

**Comment by virustotalop** [comment]
@crimsson While 1.19.2 isn't officially supported yet because I haven't tested it there shouldn't be any issue with the language config. The only thing that is possibly missing is new mobs but I'll do a check over once the plugin officially supports 1.19. Thanks again for the report and feel free to open any issues if you find any.
