### ISSUE TITLE
Potion transformation glitch

### ISSUE THREAD

**Issue by Momshroom** [virustotalop/ObsidianAuctions#18]
If you auction potions or water bottles with more than one type in your inventory... it will take all of them and convert them to whichever type you have in hand.  
Splash potions have the same issue.
Example:  I have 10 water bottles and one night vision pot, I hold the night vision pot and do /auc all:
11 night vision pots are auctioned and whoever receives them gets 11 night vision pots.
Spigot 1.11.2
Latest Obsidian auction release.

**Comment by virustotalop** [comment]
Are you sure you are running the latest version of ObsidianAuctions? That bug should have been fixed already as you can see in #6

**Comment by Momshroom** [comment]
Sigh. No, I have version 4.0.2.  Sorry for keeping bothering you with things that aren't your fault.

**Comment by virustotalop** [comment]
Its alright everyone makes mistakes.
