### ISSUE TITLE
Include a project environment

### ISSUE THREAD

**Issue by mr2013** [virustotalop/ObsidianAuctions#22]
As is, this project cannot be compiled. Could it be updated to include the eclipse, idea, netbeans, maven, and/or ant environment configured with the various dependencies?

**Comment by Set3** [comment]
Please do

**Comment by virustotalop** [comment]
I ended up converting the project to using gradle. I'm really only familiar with using eclipse but I can look into how to support other ides. Is there anything else that you would need?
