### ISSUE TITLE
1.13 update

### ISSUE THREAD

**Issue by sgdc3** [virustotalop/ObsidianAuctions#29]
@virustotalop

**Comment by virustotalop** [comment]
@sgdc3 Thanks for the ping. I've been meaning to update the plugin but the parser is still an issue. I'm going to be updating the plugin in the 1.13 branch.

**Comment by virustotalop** [comment]
1.13 support was added in the [5.0.0](https://github.com/virustotalop/ObsidianAuctions/tree/5.0.0) branch which is currently in development.
