### ISSUE TITLE
Queue auction "bug"

### ISSUE THREAD

**Issue by Malachiel87** [virustotalop/ObsidianAuctions#9]
Spigot 1.8.8 and 4.10 obsidianauction
Hi i noticed when i queue an item at auction:
1) i have a diamond in hand, and there is already a auction, i type /auc start
2) it say in queue, meanwhile i switch my hand to another item rare sword for show it to a friend
3) my auction will start, but it will take the item from my hand, and not the the diamond, my sword will go in auction.... 
It supposed to work like this?

**Comment by virustotalop** [comment]
This should be the intended behavior otherwise you could throw the item etc and it would attempt to auction it. If this behavior was changed I think too many issues would occur.
